apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespacelabellers.ops.dev
spec:
  scope: Cluster
  group: ops.dev
  names:
    kind: NamespaceLabeller
    plural: namespacelabellers
    singular: namespacelabeller
    shortNames:
      - nslb
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                targetNamespace:
                  type: string
                targetLabels:
                  type: object
                  additionalProperties:
                    type: string
              required:
                - targetNamespace
                - targetLabels
            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object

---

apiVersion: v1
kind: Namespace
metadata:
  name: vaibhav-test
  annotations:
    ops.dev/namespacelabeller: "true"
