apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-label-operator
  namespace: namespace-label-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-label-operator
rules:
  - apiGroups: ["ops.dev"]
    resources: ["namespacelabellers"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-label-operator-binding
subjects:
  - kind: ServiceAccount
    name: namespace-label-operator
    namespace: namespace-label-operator
roleRef:
  kind: ClusterRole
  name: namespace-label-operator
  apiGroup: rbac.authorization.k8s.io
