apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-sync-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: secret-sync-operator
  template:
    metadata:
      labels:
        k8s-app: secret-sync-operator
    spec:
      serviceAccountName: secret-sync-operator
      restartPolicy: Always
      containers:
        - name: secret-sync-operator
          image: vaibhavthakur/secretsync:v0.1
          command: ["python", "secret-sync.py"]
          env:
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
